[Work In Progress][failing test build] minor edits to gm17/tests/mimc.rs
It was leading to this build failure on the CLI: https://gist.github.com/savil/7e42f106b207b31082a202e27c279108

The current edits seem to fix some issues, but the replacement of
`PairingEngine` with `Field` is hitting an issue.

The compiler error is:
```
error[E0277]: the trait bound `algebra::curves::models::bls12::Bls12<algebra::curves::bls12_381::Bls12_381Parameters>: algebra::fields::Field` is not satisfied
   --> gm17/tests/mimc.rs:189:17
    |
189 |         let c = MiMCDemo::<Bls12_381> {
    |                 ^^^^^^^^^^^^^^^^^^^^^ the trait `algebra::fields::Field` is not implemented for `algebra::curves::models::bls12::Bls12<algebra::curves::bls12_381::Bls12_381Parameters>`
    |
```

I'm not sure how to proceed here. Halp?